// Generated by CoffeeScript 1.7.1
(function() {
  var redditMetaLinker, request;

  request = require('request');

  redditMetaLinker = (function() {
    function redditMetaLinker() {}

    redditMetaLinker.COMMANDS = [
      {
        rawCommand: /(^|\s)[\/\\]?r[\\\/][^\\\/\W]+/i,
        when: null,
        method: "link"
      }
    ];

    redditMetaLinker.prototype.link = function(bot, out, isPublic, from, to, command, params, message) {
      var query;
      query = /(^|\s)[\/\\]?r[\\\/][^\\\/\W]+/i.exec(message)[0].trim();
      if (query[0] === "/") {
        query = query.slice(1);
      }
      return request("http://www.reddit.com/" + query + "/about.json", function(req, data, res) {
        var parsed, s;
        parsed = JSON.parse(data.body);
        if ((parsed.error != null) || parsed.kind === "Listing") {
          return;
        }
        data = parsed.data;
        s = "";
        s += data.over18 ? "\x0304NSFW \x03" : "";
        s += "" + data.display_name + ": http://www.reddit.com" + data.url;
        return out(s);
      });
    };

    return redditMetaLinker;

  })();

  module.exports = redditMetaLinker;

}).call(this);
