// Generated by CoffeeScript 1.7.1
(function() {
  var moment, redditIRC, request;

  request = require("request");

  moment = require("moment");

  redditIRC = (function() {
    function redditIRC() {}

    redditIRC.COMMANDS = [
      {
        command: /^reddit/ig,
        when: null,
        method: "give"
      }
    ];

    redditIRC.prototype.give = function(bot, out, isPublic, from, to, command, params, message) {
      var username;
      if (params.length !== 1) {
        return;
      }
      username = params[0];
      return request("http://www.reddit.com/user/" + username + "/about.json", function(req, data, res) {
        try {
          data = JSON.parse(res).data;
          if (isPublic) {
            return out("Name: " + data.name + " | Signup: " + (moment(data.created * 1000).fromNow()) + " | LinkKarma: " + data.link_karma + " |  CommentKarma: " + data.comment_karma + " | Has gold: " + (data.is_gold ? "yup!" : "nope"));
          } else {
            return out("Name: " + data.name + " | Signup: " + (moment(data.created * 1000).fromNow()) + " | LinkKarma: " + data.link_karma + " |  CommentKarma: " + data.comment_karma + " | Has gold: " + (data.is_gold ? "yup!" : "nope"));
          }
        } catch (_error) {
          return out("Whoops! That didn't go right!");
        }
      });
    };

    return redditIRC;

  })();

  module.exports = redditIRC;

}).call(this);
