// Generated by CoffeeScript 1.7.1
(function() {
  var dwarfcraftInsulter, insults, _;

  _ = require("lodash");

  insults = ["STAHP", "Y U DO DIS", "I EHM'T UR MUM LAST NITE", "STFU"];

  dwarfcraftInsulter = (function() {
    function dwarfcraftInsulter() {}

    dwarfcraftInsulter.COMMANDS = [
      {
        rawCommand: /\b(u|e)*h+m+/ig,
        when: ["public"],
        method: "insult"
      }
    ];

    dwarfcraftInsulter.prototype.insult = function(bot, out, isPublic, from, to, command, params, message) {
      if (from.toLowerCase() !== "dwarfcraft") {
        return;
      }
      return out(insults[_.random(0, insults.length - 1)]);
    };

    return dwarfcraftInsulter;

  })();

  module.exports = dwarfcraftInsulter;

}).call(this);
