// Generated by CoffeeScript 1.7.1
(function() {
  var choose, _;

  _ = require("lodash");

  choose = (function() {
    function choose() {}

    choose.COMMANDS = [
      {
        command: /^choose/ig,
        when: null,
        method: "choose",
        commandLength: 1
      }
    ];

    choose.prototype.choose = function(bot, out, isPublic, from, to, command, params, message) {
      var choices, param;
      if (params.length === 0 || (params.length === 1 && _.isEmpty(params[0].trim()))) {
        return;
      }
      if (message.indexOf(",") !== -1) {
        params = message.split(" ").slice(1).join(" ").split(",");
      }
      choices = (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = params.length; _i < _len; _i++) {
          param = params[_i];
          _results.push(param.trim());
        }
        return _results;
      })();
      return out(("" + from + ": ") + choices[_.random(0, choices.length - 1)]);
    };

    return choose;

  })();

  module.exports = choose;

}).call(this);
